language: php

sudo: false

git:
    depth: 1

cache:
    directories:
    - $HOME/.composer
    - tests/fixtures

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--optimize-autoloader --no-interaction --no-progress"
        - COMPOSER_FLAGS=""

before_install:
    - phpenv config-rm xdebug.ini || return 0
    - composer global show hirak/prestissimo -q || travis_retry composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo

install:
    - travis_retry composer update $DEFAULT_COMPOSER_FLAGS $COMPOSER_FLAGS
    - composer info -D | sort

jobs:
    include:
    -
        stage: Code Standard
        php: 7.2
        env: COMPOSER_FLAGS="--no-dev --prefer-stable"
        script:
            - vendor/bin/phpstan analyse -l 7 src/ || travis_terminate 1
            - vendor/bin/php-cs-fixer --diff --diff-format=udiff --dry-run -v fix
            - vendor/bin/composer-require-checker check --config-file=.composer-require-checker.json composer.json || travis_terminate 1
            - composer normalize ./composer.json --dry-run

    - &TEST_JOB
        stage: Test
        php: 7.2
        script:
            - vendor/bin/parallel-lint --exclude vendor . .php_cs bin/fetch-api-docs bin/generate-classes bin/generate-metadata || travis_terminate 1
            - vendor/bin/phpunit

    -
        <<: *TEST_JOB
        stage: Test
        php: 7.1
        env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

    -
        <<: *TEST_JOB
        php: nightly

    -
        <<: *TEST_JOB
        stage: Code Coverage
        php: 7.2
        env: BNET_API_KEY=""
        script:
            - phpdbg --version 2> /dev/null || travis_terminate 0
            - phpdbg -qrr vendor/bin/phpunit -c .travis/phpunit.coverage.xml --coverage-clover build/logs/clover.xml || travis_terminate 1
            - php vendor/bin/php-coveralls -v

allow_failures:
    - php: nightly
